- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: setup NPM resource
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: Install nodejs
    ansible.builtin.yum :
      name: nodejs
      state: installed
  - name: check user exits or not
    ansible.builtin.command:
    register: output
    ignore_errors: true
  - name: create user roboshop
    become: yes
    ansible.builtin.user :
      name: roboshop
    when: output.rc != 0

  - name : /app directory exits or not
    ansible.builtin.stat :
      path: /app
    register: directory
  - name : print the directory exist stats
    ansible.builtin.debug:
       msg: "output: {{directory}}"
  - when: directory.stat.exists == False
    name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download the catalogue artifact
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name : extract the catalogue artifact
    ansible.builtin.unarchive :
      src : /tmp/catalogue.zip
      dest : /app
      remote_src : yes

  - name : Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name : copy catalogue.service
    ansible.builtin.copy :
      src : catalogue.service
      dest : /etc/systemd/system/catalogue.service

  - name : daemon reload and restart the service
    ansible.builtin.systemd:
      daemon_reload : true

  - name : copy mongo repo in yum.repos.d
    ansible.builtin.copy :
      src : mongo.repo
      dest : /etc/yum.repos.d/mongo.repo

  - name :  mongodb client software installation
    ansible.builtin.yum :
      name : mongodb-org-shell
      state : installed
  - name: install dependencies
    ansible.builtin.command: mongo --host mongo.devopspractice.tech </app/schema/catalogue.js
  - name : restart catalogue
    ansible.builtin.service :
      name : catalogue
      state : restarted
      enabled : yes
